# Generated by Django 4.1.7 on 2023-03-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('designation', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('appartment_type', models.CharField(choices=[('Meublé', 'Meublé'), ('Non-meublé', 'Non-meublé')], db_index=True, max_length=20)),
                ('rent', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rent_A', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rent_B', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('rent_C', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('unit', models.CharField(choices=[('Mois', 'Mois'), ('Jour', 'Jour'), ('Heure', 'Heure'), ('pièce', 'pièce')], db_index=True, default='Mois', max_length=20)),
                ('isAvailable', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=30)),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], db_index=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('maritalstatus', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé')], db_index=True, max_length=15, null=True)),
                ('children', models.IntegerField(db_index=True, default=0)),
                ('occupation', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('id_card_type', models.CharField(blank=True, choices=[("Carte d'électeur", "Carte d'électeur"), ('Permis de conduire', 'Permis de conduire'), ('Passeport', 'Passeport'), ('Autre', 'Autre')], db_index=True, max_length=20, null=True)),
                ('id_card_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('id_card_scan', models.ImageField(default='default-id.jpg', upload_to='id_cards')),
                ('category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, max_length=1, null=True)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('isComplete', models.BooleanField(db_index=True, default=False)),
                ('invoiced', models.BooleanField(blank=True, db_index=True, null=True)),
                ('appartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.appartment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RentalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('isComplete', models.BooleanField(db_index=True, default=False)),
                ('due_amount', models.FloatField(db_index=True, default=0)),
                ('paid_amount', models.FloatField(db_index=True, default=0)),
                ('pending_payment', models.FloatField(db_index=True, default=0)),
                ('cash', models.FloatField(db_index=True, default=0)),
                ('change', models.FloatField(db_index=True, default=0)),
                ('isPaid', models.BooleanField(db_index=True, default=False)),
                ('invoiced', models.BooleanField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(db_index=True, to='administration.rentpayment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('rent_paid_on', models.DateTimeField(db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appartment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.appartment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='appartment',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.tag'),
        ),
    ]
