# Generated by Django 4.1.7 on 2023-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcontract',
            old_name='rent_paid_on',
            new_name='next_payment_on',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_card_scan',
            field=models.ImageField(blank=True, default='default-id.png', null=True, upload_to='id_cards'),
        ),
    ]
