# Generated by Django 4.1.7 on 2023-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_rent_paid_on_rentalcontract_next_payment_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='next_payment_on',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
