# Generated by Django 4.1.7 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_rentalcontract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='next_payment_on',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
