# Generated by Django 4.1.7 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_rentalcontract_deposit_rentalcontract_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='appartment',
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='appartment',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='administration.appartment'),
        ),
    ]
