# Generated by Django 4.1.7 on 2023-03-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_rentalcontract_appartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='appartment',
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='appartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.appartment'),
        ),
    ]
