# Generated by Django 4.1.7 on 2023-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_rentalcontract_appartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='isTerminated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='isTerminated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
