# Generated by Django 4.1.7 on 2023-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_rentalcontract_isterminated_tenant_isterminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='cash',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='change',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='due_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='isPaid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='paid_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='pending_payment',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='invoiced',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='RentalInvoice',
        ),
    ]
