# Generated by Django 4.1.7 on 2023-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_remove_rentpayment_invoiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='paying_for',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
