# Generated by Django 4.1.7 on 2023-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_rentpayment_paying_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='invoiced',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
