# Generated by Django 4.1.7 on 2023-03-24 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0015_income_disbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('department', models.CharField(choices=[('', ''), ('', '')], db_index=True, max_length=20)),
                ('salary', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('isAvailable', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appartment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('isTerminated', models.BooleanField(db_index=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.tenant')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.position')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=30)),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], db_index=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('maritalstatus', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé')], db_index=True, max_length=15, null=True)),
                ('children', models.IntegerField(db_index=True, default=0)),
                ('department', models.CharField(blank=True, choices=[('', ''), ('', '')], db_index=True, max_length=10, null=True)),
                ('id_card_type', models.CharField(blank=True, choices=[("Carte d'électeur", "Carte d'électeur"), ('Permis de conduire', 'Permis de conduire'), ('Passeport', 'Passeport'), ('Autre', 'Autre')], db_index=True, max_length=20, null=True)),
                ('id_card_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('id_card_scan', models.ImageField(blank=True, default='default-id.png', null=True, upload_to='id_cards')),
                ('isTerminated', models.BooleanField(db_index=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.position')),
            ],
        ),
    ]
