# Generated by Django 4.1.7 on 2023-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_position_alter_appartment_slug_workcontract_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='slug',
        ),
    ]
