# Generated by Django 4.1.7 on 2023-03-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_remove_appartment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outsourcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('isTerminated', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='outsourcer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.outsourcer'),
        ),
    ]
