# Generated by Django 4.1.7 on 2023-03-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_enterprise_partner_remove_appartment_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='outsourcer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.partner'),
        ),
        migrations.DeleteModel(
            name='Outsourcer',
        ),
    ]
