# Generated by Django 4.1.7 on 2023-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_alter_position_outsourcer_delete_outsourcer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='isTerminated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
