# Generated by Django 4.1.7 on 2023-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_partner_isterminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], db_index=True, max_length=20, null=True),
        ),
    ]
