# Generated by Django 4.1.7 on 2023-03-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_alter_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
