# Generated by Django 4.1.7 on 2023-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_remove_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='workcontract',
            name='department',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], db_index=True, max_length=10, null=True),
        ),
    ]
