# Generated by Django 4.1.7 on 2023-03-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_remove_employee_department_workcontract_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workcontract',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workcontract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.employee'),
        ),
    ]
