# Generated by Django 4.1.7 on 2023-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_alter_salary_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Compte caisse/liquide', 'Compte caisse/liquide'), ('Compte bancaire courant ou carte', 'Compte bancaire courant ou carte'), ('Compte bancaire épargne', 'Compte bancaire épargne')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='isClosed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='swift',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='description',
            field=models.CharField(blank=True, db_index=True, default='Paiement salaire', max_length=200, null=True),
        ),
    ]
