# Generated by Django 4.1.7 on 2023-03-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_bankaccount_account_holder_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='initial_balance',
        ),
    ]
