# Generated by Django 4.1.7 on 2023-03-25 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0030_transferout_transferin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('to_account', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('amount', models.FloatField(db_index=True, default=0)),
                ('description', models.CharField(blank=True, db_index=True, default='Virement interne', max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transferout',
            name='from_account',
        ),
        migrations.DeleteModel(
            name='TransferIn',
        ),
        migrations.DeleteModel(
            name='TransferOut',
        ),
    ]
