# Generated by Django 4.1.7 on 2023-03-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_transfer_remove_transferout_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bankaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bankaccount'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bankaccount'),
        ),
    ]
