# Generated by Django 4.1.7 on 2023-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_disbursement_account_income_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='added_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='added_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='added_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
