# Generated by Django 4.1.7 on 2023-03-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_disbursement_added_amount_income_added_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='added_amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='added_amount',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='added_amount',
        ),
    ]
