# Generated by Django 4.1.7 on 2023-03-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_remove_disbursement_added_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='entreprise',
            field=models.CharField(blank=True, choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='entreprise',
            field=models.CharField(blank=True, choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='entreprise',
            field=models.CharField(blank=True, choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100, null=True),
        ),
    ]
