# Generated by Django 4.1.7 on 2023-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_alter_disbursement_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='entreprise',
            field=models.CharField(choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='entreprise',
            field=models.CharField(choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='entreprise',
            field=models.CharField(choices=[('Appartements', 'Appartements'), ('Génie civil', 'Génie civil'), ('Ferme', 'Ferme')], db_index=True, max_length=100),
        ),
    ]
