# Generated by Django 4.1.7 on 2023-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_alter_disbursement_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='entreprise',
            field=models.CharField(choices=[('DNK Appartements', 'DNK Appartements'), ('DNK Génie civil', 'DNK Génie civil'), ('DNK Ferme', 'DNK Ferme')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='entreprise',
            field=models.CharField(choices=[('DNK Appartements', 'DNK Appartements'), ('DNK Génie civil', 'DNK Génie civil'), ('DNK Ferme', 'DNK Ferme')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='check_status',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='entreprise',
            field=models.CharField(choices=[('DNK Appartements', 'DNK Appartements'), ('DNK Génie civil', 'DNK Génie civil'), ('DNK Ferme', 'DNK Ferme')], db_index=True, max_length=100),
        ),
    ]
