# Generated by Django 4.1.7 on 2023-03-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_alter_disbursement_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='check_status',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
