# Generated by Django 4.1.7 on 2023-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_alter_enterprise_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='impf',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='irl',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
